---
- name: Ensure Needed packages is installed
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ needed_packages_debian }}"

- name: Adding ElasticSearch apt_key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present
    validate_certs: False

- name: Add APT repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
    update_cache: yes