---
- name: Ensure pre-dependency is already installed
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - unzip

- name: Adding ElasticSearch apt_key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Add APT repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
    update_cache: yes