---
- name: Ensure pre-dependency is already installed
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip

- name: Adding ElasticSearch repo
  yum_repository:
    name: beats
    description: ELK Repo
    baseurl: https://artifacts.elastic.co/packages/{{ elasticsearch_major_version }}.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: yes



