---
- name: Install Docker Compose
  get_url:
    url: 'https://github.com/docker/compose/releases/download/1.18.0/docker-compose-Linux-{{ ansible_architecture }}'
    dest: '/usr/local/bin/docker-compose'
    force: True
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: ansible_os_family != 'Windows'