---
- name: Receiving variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure needed packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ needed_packages }}"

- include: deb_install.yml
  when: ansible_os_family == 'Debian'

- include: rhel_install.yml
  when: ansible_os_family == 'RedHat'

- name: Purging distribution-provided packages
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ os_distribution_docker }}"

- name: Ensure packages are installed
  package:
    name: "docker-{{ docker_edition }}"
    state: present

- name: Add specific users to 'docker' group
  user:
    name: '{{ item }}'
    groups: 'docker'
    append: True
  with_items: '{{ docker_users }}'
  when: item|d()

- include: docker-compose.yml
  when: docker_install_docker_compose